version: "2"

services:

  masterecho:
    container_name: masterecho
    build: .
    #image: ctftraining/westerns_2018_shrine
    restart: always
    ports:
      - "127.0.0.1:8081:5000"
    environment:
      - flag=CITYF{SsTi_4nd_w@f_t0gether}
